name: restaurantbase
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  salomon_bottom_bar: ^3.3.2
  provider: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/menu/coffee.jpg
    - assets/menu/wine.jpg
    - assets/menu/food1.jpg
    - assets/menu/food2.jpg
    - assets/menu/food3.jpg
    - assets/menu/food4.jpg
    - assets/menu/food5.jpg
    - assets/menu/food6.jpg
    - assets/menu/food7.jpg

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700  

